/*CREATE DATABASE RETEAA */
GO
USE RETEAA
CREATE TABLE ROL(cod_r INT PRIMARY KEY, nume nvarchar(50));
CREATE TABLE UTILIZATOR(cod_u INT PRIMARY KEY, nume nvarchar(50), parola nvarchar(50), cod_r int FOREIGN KEY REFERENCES ROL(cod_r) ON UPDATE CASCADE ON DELETE SET NULL);
CREATE TABLE POSTARE(cod_p INT PRIMARY KEY, nume nvarchar(50));
CREATE TABLE TAG(cod_t INT PRIMARY KEY, nume nvarchar(50));
CREATE TABLE POSTARETAG(cod_p INT FOREIGN KEY REFERENCES POSTARE(cod_p) ON UPDATE CASCADE ON DELETE CASCADE,
						cod_t INT FOREIGN KEY REFERENCES TAG(cod_t) ON UPDATE CASCADE ON DELETE CASCADE,
						CONSTRAINT PK_POSTARETAG PRIMARY KEY(cod_p, cod_t));
CREATE TABLE COMENTARIU(cod_c INT PRIMARY KEY, continut nvarchar(50), data DATE, cod_u INT FOREIGN KEY REFERENCES UTILIZATOR(cod_u) ON UPDATE CASCADE ON DELETE SET NULL);


